### ISSUE TITLE
Slack channel for the development/questions of kubebuilder-declarative-pattern

### ISSUE THREAD

**Issue by JeffLuoo** [kubernetes-sigs/kubebuilder-declarative-pattern#231]
Currently the slack link of the project redirects to the broad `kubernetes` channel and I wonder shall we create a channel for development/questions about the project specifically? I see some people asking questions about this project under the `kubebuilder` channel as well.

**Comment by atoato88** [comment]
Thank you for suggesting :smile: 
I think the place for questions about this repository is `kubebuilder` channel, because this repository is a part of `kubebuilder` project.
It's better to create new channel if topics of this repository grow on `kubebuilder` channel.
But I don't think so currently, because topics are something few.

@justinsb 
WDYT?

**Comment by JeffLuoo** [comment]
Thanks for the reply!

**Comment by atoato88** [comment]
/close
I close this issue because that I got a comment from issue author.
Feel free to add comment if any extras.
